//! Generates the preset set the binary carries, from `presets/` at the repo
//! root. Adding a shipped preset is dropping a `.toml` in there: no Rust to
//! edit, and no second place to keep a description in sync.
//!
//! This is also where the filename-stem rule is fatal. We control what ships,
//! so a preset whose stem and declared `name` disagree is a bug that must never
//! be published — the same check is only a reason to skip a preset someone left
//! on disk.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

// The rule itself lives in the crate, and is compiled here a second time rather
// than copied. Same rule, two severities.
#[path = "src/preset_name.rs"]
mod preset_name;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let dir = Path::new(&manifest).join("presets");

    // Cargo rescans the directory, so a new file is picked up as readily as an
    // edit to one that is already there.
    println!("cargo:rerun-if-changed=presets");
    println!("cargo:rerun-if-changed=src/preset_name.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("could not read {}: {e}", dir.display()))
        .map(|entry| entry.expect("could not read a directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "toml"))
        .collect();
    files.sort();

    let mut generated = String::from(
        "// Generated by build.rs from `presets/`. Do not edit.\n\
         \n\
         /// A preset embedded at build time: its filename stem, the description\n\
         /// declared inside it, and the flow itself.\n\
         pub struct Shipped {\n    \
             pub name: &'static str,\n    \
             pub description: &'static str,\n    \
             pub contents: &'static str,\n\
         }\n\
         \n\
         /// Every `.toml` in `presets/`, in filename order.\n\
         pub static SHIPPED: &[Shipped] = &[\n",
    );

    for path in &files {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("{} has no usable filename", path.display()));
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("could not read {}: {e}", path.display()));
        let flow: toml::Table = text
            .parse()
            .unwrap_or_else(|e| panic!("{} is not valid TOML: {e}", path.display()));

        let name = field(&flow, "name");
        if let Err(reason) = preset_name::check(stem, name) {
            panic!("{}: {reason}", path.display());
        }
        // The other half of what makes a preset usable. Discovery skips an
        // on-disk preset that declares no stages; a shipped one has to fail
        // here instead, because nothing downstream checks what we embed.
        if flow
            .get("stage")
            .and_then(|value| value.as_array())
            .is_none_or(|stages| stages.is_empty())
        {
            panic!("{}: declares no stages", path.display());
        }

        writeln!(
            generated,
            "    Shipped {{ name: {stem:?}, description: {:?}, contents: include_str!({:?}) }},",
            field(&flow, "description"),
            path.display().to_string(),
        )
        .expect("writing to a String cannot fail");
    }
    generated.push_str("];\n");

    let out =
        PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("shipped.rs");
    std::fs::write(&out, generated)
        .unwrap_or_else(|e| panic!("could not write {}: {e}", out.display()));
}

/// A top-level string field, or empty when the file does not declare one — the
/// checks below turn absence into a message, rather than reading as a mismatch.
fn field<'a>(flow: &'a toml::Table, key: &str) -> &'a str {
    flow.get(key).and_then(|value| value.as_str()).unwrap_or("")
}
